# YAML Solution for 01_Deploy_Apache_Web_Server_on_Kubernetes_Cluster
apiVersion: v1
kind: Namespace
metadata:
  name: httpd-namespace-datacenter

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deployment-datacenter
  namespace: httpd-namespace-datacenter
spec:
  replicas: 2 # Desired number of identical pods
  selector:
    matchLabels:
      app: httpd
  template:
    metadata:
      labels:
        app: httpd
    spec:
      containers:
        - name: httpd-container
          image: httpd:latest
          ports:
            - containerPort: 80


---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service-datacenter
  namespace: httpd-namespace-datacenter
spec:
  selector:
    app: httpd
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30004
  type: NodePort
