apiVersion: apps/v1
kind: Deployment
metadata:
  name: node-app-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: node
  template:
    metadata:
      labels:
        app: node
    spec:
      containers:
        - name: node-app-container
          image: gcr.io/kodekloud/centos-ssh-enabled:node
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  name: node-app-service
spec:
  type: NodePort
  selector:
    app: node # This should match the labels of your Pods
  ports:
    - protocol: TCP
      port: 8080 # The port the Service exposes within the cluster
      targetPort: 8080 # The port your application in the Pod is listening on
      nodePort: 30012