---
apiVersion: v1
kind: Namespace
metadata:
  name: devops

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpd-deploy
  namespace: devops

spec:
  replicas: 4 # Desired number of pod replicas
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 2
  selector:
    matchLabels:
      app: apache
  template:
    metadata:
      labels:
        app: apache
    spec:
      containers:
        - name: httpd
          image: httpd:2.4.28 # Container image to use
          ports:
            - containerPort: 80 # Port exposed by the container


---
apiVersion: v1
kind: Service
metadata:
  name: httpd-service
  namespace: devops
spec:
  type: NodePort
  selector:
    app: apache # This should match the 'app' label of your Pods
  ports:
    - protocol: TCP
      port: 80 # The port the service exposes internally within the cluster
      targetPort: 80 # The port on the Pod that the service targets
      nodePort: 30008


---
# Update deployment image
kubectl set image deployment/httpd-deploy httpd=httpd:2.4.43 -n devops
  
  # Rollback to previous version
kubectl rollout undo deployment/httpd-deploy -n devops
