apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-deployment-nautilus
  labels:
    app: python-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
        - name: python-container
          image: poroko/flask-demo-app
          ports:
            - containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: python-service-nautilus
  labels:
    app: python-app
spec:
  type: NodePort
  selector:
    app: python-app
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 32345
